services:
  mongo:
    image: mongo:6
    container_name: clip_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: clip_backend
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=clipdb
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - ./data/images:/app/data/images
      - ./data:/app/data

  frontend:
    build: ./frontend
    container_name: clip_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data:
